language: node_js
node_js:
  - '10.15.3'

install:
  - yarn install

script:
  - yarn test
  - codecov -f coverage/*.json

branches:
  only:
    - master

env:
  - CODECOV_TOKEN="939a5e53-2028-4db1-a208-8c75291ee56d"
